dubbo:
  application:
    name: job-dubbo
  annotation:
    package: com.wz.job.demo.dubbo.service
  protocol:
    name: dubbo
    port: -1
    accessLog: true
  provider:
    timeout: 3000
    retries: 1
    delay: -1
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
    register: true
    subscribe: true

mq:
  nameServerAddress: 10.9.20.64:9876
  producerGroup: TestGroup
  instanceName: Producer
  tag: wz
  subscriberID: CONSUMER_TEST
  topic: TOPIC_TEST