spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy_job?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 1
    maxActive: 100
    initialSize: 10
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  freemarker:
    enabled: true
    order: 1
    suffix: .html
    template-loader-path: classpath:/ftl/
    allow-request-override: false
    allow-session-override: false
    cache: true
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true

mybatis:
  mapperLocations: classpath*:com/wz/job/common/mapper/*.xml
  typeAliasesPackage: com.wz.job.common.model

zookeeper:
  host: 127.0.0.1:2181
  timeout: 1000
  retries: 3

server:
  port: 8088